server:
  port: 8050

spring:
  application:
    name: xfc-spring-cloud-nacos-learning  #微服务名称

  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        cluster-name: SH
        metadata:
          version: v2