server:
  port: 1230
eureka:
  client:
    ##  取消自我注册
    register-with-eureka: false
    ##  关闭服务检索（因为自己本来就拥有所有服务资源）
    fetch-registry: false
    eureka-server-u-r-l-context: http://localhost:${server.port}/eurka