server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/itxingfeichen/xfc-spring-cloud-config-repo
          #          uri: /Users/chenxingfei/WorkSpace/xfc-spring-cloud-config-repo
          username: xingfeichen@163.com
          password: xf1123581321
  application:
    name: config-server
management:
  endpoint:
    refresh:
      enabled: false