spring:
  application:
    name: user-consumer
server:
  port: 8082
  eureka:
    port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${server.eureka.port}/eureka
management:
  server:
    ssl:
      enabled: false